### ISSUE TITLE
SigScan Failed

### ISSUE THREAD

**Issue by luigistyle** [welikethestock/FCND-HighPingKick-Patch#1]
Been trying to play with a friend who lives far away from me, I tried to inject the patch but the console never gets past

Waiting for game...
Found game (pid 17244)
OpenProcess successful (handle 0000000000000094)
VirtualAllocEx successful (address 0000023519830000)
WriteProcessMemory successful
I also get an error that states "SigScan Failed".

We'd really like be able to play this game together so any help would be greatly appreciated!

**Comment by welikethestock** [comment]
Contact me here to assist me finding new signature

https://steamcommunity.com/id/ADB-BUTINACA/

**Comment by welikethestock** [comment]
Updated
